### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by iCaran** [michaelneuper/hugo-texify3#9]
pleas add a guide for tags, i can't figure out where they are, both Tags and Categories, how do i edit them?

**Comment by michaelneuper** [comment]
Tags and categories are added in the frontmatter of your post's content file:
``` yaml
---
title: "Post Title"
categories: ['category']
tags: ['tag1', 'tag2']
---
```
